# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Harific < Formula
  desc "Lightning-fast HAR file viewer and analysis tool with TUI and mock server"
  homepage "https://pb33f.io/harific"
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/pb33f/harific/releases/download/v0.0.4/harific_0.0.4_darwin_x86_64.tar.gz"
      sha256 "328dbd9c263bde0f0b82995f3c10709156fb5d8cfe220e4287b9583eaaccbd53"

      def install
        bin.install "harific"
      end
    end
    on_arm do
      url "https://github.com/pb33f/harific/releases/download/v0.0.4/harific_0.0.4_darwin_arm64.tar.gz"
      sha256 "03fb32ebcac2b0fccb41c6e32407bf68407e3c448bacbb142e03a39e10a10d33"

      def install
        bin.install "harific"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pb33f/harific/releases/download/v0.0.4/harific_0.0.4_linux_x86_64.tar.gz"
        sha256 "86b2617cff8622524cac25a1b06187c82a6c1822cfb70dd918f6698b8d4395eb"

        def install
          bin.install "harific"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pb33f/harific/releases/download/v0.0.4/harific_0.0.4_linux_arm64.tar.gz"
        sha256 "beedf6fddb2cb62a0a69c11ac9e6b7d8a72b492fd15a679fd90c21188e74023f"

        def install
          bin.install "harific"
        end
      end
    end
  end
end
