# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Harific < Formula
  desc "Lightning-fast HAR file viewer and analysis tool with TUI and mock server"
  homepage "https://pb33f.io/harific"
  version "0.0.6"

  on_macos do
    on_intel do
      url "https://github.com/pb33f/harific/releases/download/v0.0.6/harific_0.0.6_darwin_x86_64.tar.gz"
      sha256 "67ddd8b4873bfe4118fdd666847cf6794dfe8f2b984e3e779c1baa2070f09f3a"

      def install
        bin.install "harific"
      end
    end
    on_arm do
      url "https://github.com/pb33f/harific/releases/download/v0.0.6/harific_0.0.6_darwin_arm64.tar.gz"
      sha256 "da72881193b0b1a277620cecd53b2c6d06321a91cbf84ad9e1e960b80364fb54"

      def install
        bin.install "harific"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pb33f/harific/releases/download/v0.0.6/harific_0.0.6_linux_x86_64.tar.gz"
        sha256 "53102a1b6513ca5e9e996750a1b15d64e0688bb73914cef2fbcb47e70a090129"

        def install
          bin.install "harific"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pb33f/harific/releases/download/v0.0.6/harific_0.0.6_linux_arm64.tar.gz"
        sha256 "59a36605e45b9025d78fc0df8a6ee0a3df7837a6aa403cc0d420234371435fbb"

        def install
          bin.install "harific"
        end
      end
    end
  end
end
