# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Harific < Formula
  desc "Lightning-fast HAR file viewer and analysis tool with TUI and mock server"
  homepage "https://pb33f.io/harific"
  version "0.0.5"

  on_macos do
    on_intel do
      url "https://github.com/pb33f/harific/releases/download/v0.0.5/harific_0.0.5_darwin_x86_64.tar.gz"
      sha256 "a5f04d92e9ddad556b0f805224032091d48979ad813e6573f342da19ee92f137"

      def install
        bin.install "harific"
      end
    end
    on_arm do
      url "https://github.com/pb33f/harific/releases/download/v0.0.5/harific_0.0.5_darwin_arm64.tar.gz"
      sha256 "9a140b0a58778d2bd683c8ca21b518bf70cfc4e010c03d80df927cfac82cf39a"

      def install
        bin.install "harific"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pb33f/harific/releases/download/v0.0.5/harific_0.0.5_linux_x86_64.tar.gz"
        sha256 "85e704fd79e13e7efcbc4fae708f8429bdf35543de0c947971718c22ae0b745b"

        def install
          bin.install "harific"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pb33f/harific/releases/download/v0.0.5/harific_0.0.5_linux_arm64.tar.gz"
        sha256 "731b29901e8133b9374b1228dc40d01c1c99d8c1bc1734862400233bef3eb388"

        def install
          bin.install "harific"
        end
      end
    end
  end
end
