# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpenapiChanges < Formula
  desc "The worlds sexiest OpenAPI diffing and change detection engine"
  homepage "https://pb33f.io/openapi-changes"
  version "0.0.74"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pb33f/openapi-changes/releases/download/v0.0.74/openapi-changes_0.0.74_darwin_x86_64.tar.gz"
      sha256 "3186cc40c1b89d7114eedf53d2254c6a97f160f077d9b8c22b35fa3272595d8b"

      def install
        bin.install "openapi-changes"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pb33f/openapi-changes/releases/download/v0.0.74/openapi-changes_0.0.74_darwin_arm64.tar.gz"
      sha256 "5d36c868a971c1cdea01ca223aa3f7aa9654c4105976c9e8cfee3ac17eae2486"

      def install
        bin.install "openapi-changes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pb33f/openapi-changes/releases/download/v0.0.74/openapi-changes_0.0.74_linux_x86_64.tar.gz"
        sha256 "fac996cdeaf8a2f468b155aa0f5ee4a17f26766b0ffd9bdeb2566df6a0d4de27"

        def install
          bin.install "openapi-changes"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pb33f/openapi-changes/releases/download/v0.0.74/openapi-changes_0.0.74_linux_arm64.tar.gz"
        sha256 "8ed6d0aa0cbca79b9a61b523eb45d0498abe47d2f369742e7e23797e0b8f2893"

        def install
          bin.install "openapi-changes"
        end
      end
    end
  end
end
