# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpenapiChanges < Formula
  desc "The worlds sexiest OpenAPI diffing and change detection engine"
  homepage "https://pb33f.io/openapi-changes"
  version "0.0.87"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pb33f/openapi-changes/releases/download/v0.0.87/openapi-changes_0.0.87_darwin_x86_64.tar.gz"
      sha256 "638778cacef0bd14753ad3f1d4201e2a9d0ad6ea089a2a894f63caf12dfba752"

      def install
        bin.install "openapi-changes"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pb33f/openapi-changes/releases/download/v0.0.87/openapi-changes_0.0.87_darwin_arm64.tar.gz"
      sha256 "2908555207bfa08a2dd7d43dc5887bcdc2835fbfb1e94fe36f90c3b06a76b650"

      def install
        bin.install "openapi-changes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pb33f/openapi-changes/releases/download/v0.0.87/openapi-changes_0.0.87_linux_x86_64.tar.gz"
      sha256 "1a188b00e0ebc1f4ef73f4af50a611cc34d27179ee361df0538b16c24324e00a"
      def install
        bin.install "openapi-changes"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pb33f/openapi-changes/releases/download/v0.0.87/openapi-changes_0.0.87_linux_arm64.tar.gz"
      sha256 "e9b9f35cf642b6ae445efe1d68191a91794746e1a088d29cf2f75d46ad3a10fa"
      def install
        bin.install "openapi-changes"
      end
    end
  end
end
