# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpenapiChanges < Formula
  desc "The worlds sexiest OpenAPI diffing and change detection engine"
  homepage "https://pb33f.io/openapi-changes"
  version "0.0.68"

  on_macos do
    on_intel do
      url "https://github.com/pb33f/openapi-changes/releases/download/v0.0.68/openapi-changes_0.0.68_darwin_x86_64.tar.gz"
      sha256 "c10457bdf0e24598632d5cbe3382c9832c1d44fe298583cf0ccc36b47196df33"

      def install
        bin.install "openapi-changes"
      end
    end
    on_arm do
      url "https://github.com/pb33f/openapi-changes/releases/download/v0.0.68/openapi-changes_0.0.68_darwin_arm64.tar.gz"
      sha256 "3a47ead3d7f62e69a6eff4cdf9110f9d8df185b5b86735fcaaa6dd4fe0d9e622"

      def install
        bin.install "openapi-changes"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pb33f/openapi-changes/releases/download/v0.0.68/openapi-changes_0.0.68_linux_x86_64.tar.gz"
        sha256 "edb314f3f76ff2168b6d1ec54a65e817192d64b64c5cd184159701abc52c1dbb"

        def install
          bin.install "openapi-changes"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pb33f/openapi-changes/releases/download/v0.0.68/openapi-changes_0.0.68_linux_arm64.tar.gz"
        sha256 "234743f173acc0dc823e9330f55f7f551e0de9c730c56b939aa788dc95eb5e66"

        def install
          bin.install "openapi-changes"
        end
      end
    end
  end
end
