# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wiretap < Formula
  desc "The worlds coolest OpenAPI compliance dev HTTP proxy"
  homepage "https://pb33f.io/wiretap"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pb33f/wiretap/releases/download/v0.0.7/wiretap_0.0.7_darwin_amd64.tar.gz"
      sha256 "d915903db4cf1fcbeff131ae182f455f2ea50a140b07d5566243d0fff51330c1"

      def install
        bin.install "wiretap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pb33f/wiretap/releases/download/v0.0.7/wiretap_0.0.7_darwin_arm64.tar.gz"
      sha256 "7cc60de2626c989da743248db420a8673969bee8b082e6780b99ed43a7057e96"

      def install
        bin.install "wiretap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pb33f/wiretap/releases/download/v0.0.7/wiretap_0.0.7_linux_amd64.tar.gz"
      sha256 "5922b409f135f3ee62ffb36af041bcf19ca15b07908e82bf1da8d0213cd83920"

      def install
        bin.install "wiretap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pb33f/wiretap/releases/download/v0.0.7/wiretap_0.0.7_linux_arm64.tar.gz"
      sha256 "86b2f5f95b3f895bc51e50d45feab4e79a6e65b861523e2dd74f92b1167f250d"

      def install
        bin.install "wiretap"
      end
    end
  end
end
