# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wiretap < Formula
  desc "The worlds coolest OpenAPI compliance dev HTTP proxy"
  homepage "https://pb33f.io/wiretap"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pb33f/wiretap/releases/download/v0.1.5/wiretap_0.1.5_darwin_x86_64.tar.gz"
      sha256 "abc195901d02c28654edb4e55e11470fc4d785d47f33e6166c6ee63d0cf78fcd"

      def install
        bin.install "wiretap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pb33f/wiretap/releases/download/v0.1.5/wiretap_0.1.5_darwin_arm64.tar.gz"
      sha256 "d1af03b5c973c43a2fe2a77f2dd3ae2512ee58bd27ef50f45d71ccae41eb2fb1"

      def install
        bin.install "wiretap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pb33f/wiretap/releases/download/v0.1.5/wiretap_0.1.5_linux_x86_64.tar.gz"
      sha256 "64e4bf3492d28b549c79820b3e1270d1e97b6fa025b0eed0bb21367096ada941"

      def install
        bin.install "wiretap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pb33f/wiretap/releases/download/v0.1.5/wiretap_0.1.5_linux_arm64.tar.gz"
      sha256 "307d2bef06bc40cad098c546a276da4991e7fca15c5edd9e0af971e36348ec29"

      def install
        bin.install "wiretap"
      end
    end
  end
end
