# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wiretap < Formula
  desc "The worlds coolest OpenAPI compliance dev HTTP proxy"
  homepage "https://pb33f.io/wiretap"
  version "0.0.48"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pb33f/wiretap/releases/download/v0.0.48/wiretap_0.0.48_darwin_arm64.tar.gz"
      sha256 "22a5a17f1a39ac4ae93879b4dc1d48648f9ae518f1c53451b7b3e93954dbf575"

      def install
        bin.install "wiretap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pb33f/wiretap/releases/download/v0.0.48/wiretap_0.0.48_darwin_x86_64.tar.gz"
      sha256 "b19c9b6448ad82ec562f218516d7700b2184dfc47a8e3a96dd651cf5817ea751"

      def install
        bin.install "wiretap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pb33f/wiretap/releases/download/v0.0.48/wiretap_0.0.48_linux_x86_64.tar.gz"
      sha256 "cf14cd64b6a224e6347a8cd5313056c335ddc4c2ee15a4b7cb645316771b85f9"

      def install
        bin.install "wiretap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pb33f/wiretap/releases/download/v0.0.48/wiretap_0.0.48_linux_arm64.tar.gz"
      sha256 "452748a49e14eda4976f288b16001809001bc4d27f41e09ca9e67c5c8339383b"

      def install
        bin.install "wiretap"
      end
    end
  end
end
