# This file was generated by GoReleaser. DO NOT EDIT.
cask "openapi-changes" do
  version "0.2.2"

  on_macos do
    on_intel do
      url "https://github.com/pb33f/openapi-changes/releases/download/v#{version}/openapi-changes_#{version}_darwin_x86_64.tar.gz"
      sha256 "5db659c09dd26733c0a784216ada6899f367de74885de578710399963d40ba55"
    end
    on_arm do
      url "https://github.com/pb33f/openapi-changes/releases/download/v#{version}/openapi-changes_#{version}_darwin_arm64.tar.gz"
      sha256 "2f883ab3c448a1ee2f8c74a4546ee00945d1fc7ac794ffa140cd1a64bbee877e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pb33f/openapi-changes/releases/download/v#{version}/openapi-changes_#{version}_linux_x86_64.tar.gz"
      sha256 "bdcec884e965371548af94fd85bb20a98ea5965e0f7b40e26f93bd3eb7653a66"
    end
    on_arm do
      url "https://github.com/pb33f/openapi-changes/releases/download/v#{version}/openapi-changes_#{version}_linux_arm64.tar.gz"
      sha256 "fc539466e05cc65ed3df637757320c631f58288bd8ff2c454a8df33bde1aa355"
    end
  end

  name "openapi-changes"
  desc "The worlds most powerful OpenAPI diffing and change detection engine"
  homepage "https://pb33f.io/openapi-changes/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openapi-changes"

  # No zap stanza required

end
