# This file was generated by GoReleaser. DO NOT EDIT.
cask "openapi-changes" do
  version "0.2.3"

  on_macos do
    on_intel do
      url "https://github.com/pb33f/openapi-changes/releases/download/v#{version}/openapi-changes_#{version}_darwin_x86_64.tar.gz"
      sha256 "3b297fd57c03da92ff45e786fc69731edcac2dacfa6febed0a23762db982a9cf"
    end
    on_arm do
      url "https://github.com/pb33f/openapi-changes/releases/download/v#{version}/openapi-changes_#{version}_darwin_arm64.tar.gz"
      sha256 "9aa295a80fd46ec415f25243efa7b566bcad310c3473cd3e5c11692244f13869"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pb33f/openapi-changes/releases/download/v#{version}/openapi-changes_#{version}_linux_x86_64.tar.gz"
      sha256 "cc55f3cfb958319d8ce862b1c596816828fcf4b8c0325ccb7ea33b3b9bc134ad"
    end
    on_arm do
      url "https://github.com/pb33f/openapi-changes/releases/download/v#{version}/openapi-changes_#{version}_linux_arm64.tar.gz"
      sha256 "69464280b8d83f1e8ea429f10ee3135cf74f72227361b2d609833e4a803c2cfa"
    end
  end

  name "openapi-changes"
  desc "The worlds most powerful OpenAPI diffing and change detection engine"
  homepage "https://pb33f.io/openapi-changes/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openapi-changes"

  # No zap stanza required

end
