# This file was generated by GoReleaser. DO NOT EDIT.
cask "openapi-changes" do
  version "0.2.1"

  on_macos do
    on_intel do
      url "https://github.com/pb33f/openapi-changes/releases/download/v#{version}/openapi-changes_#{version}_darwin_x86_64.tar.gz"
      sha256 "c64346ea7fde3f89ac2d085c2579b20a931aea362d75d8be3d08a031617e559b"
    end
    on_arm do
      url "https://github.com/pb33f/openapi-changes/releases/download/v#{version}/openapi-changes_#{version}_darwin_arm64.tar.gz"
      sha256 "1ca3de7e816bb056056482796e46d116c49b95211ba13ab5b0437dee6ccf5329"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pb33f/openapi-changes/releases/download/v#{version}/openapi-changes_#{version}_linux_x86_64.tar.gz"
      sha256 "c3d6b7b58015ecffa4c5a96291d193cc88d841d0fee87e3b014320a03b01ea32"
    end
    on_arm do
      url "https://github.com/pb33f/openapi-changes/releases/download/v#{version}/openapi-changes_#{version}_linux_arm64.tar.gz"
      sha256 "c532db45b7fb3a591b2e03ddcebcee16a0deaf3e7cfd48a18b7e80ad9cbff3eb"
    end
  end

  name "openapi-changes"
  desc "The worlds most powerful OpenAPI diffing and change detection engine"
  homepage "https://pb33f.io/openapi-changes/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openapi-changes"

  # No zap stanza required

end
