# This file was generated by GoReleaser. DO NOT EDIT.
cask "printing-press" do
  version "0.0.22"

  on_macos do
    on_intel do
      sha256 "9ae12658e384fb362f0e65090c1edebefa54d779443f66718a77a677f21b52ad"
      url "https://github.com/pb33f/printing-press/releases/download/v#{version}/printing-press_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8229a2512523d6dd6bd11536c93a9ad184460fcb728eaf58ca4be35b759f2a54"
      url "https://github.com/pb33f/printing-press/releases/download/v#{version}/printing-press_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fd3e7a5f5de1275d3410631cd7d62876e79f41cf934d0578692e2485c8e4ca2b"
      url "https://github.com/pb33f/printing-press/releases/download/v#{version}/printing-press_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b0386ca09495b55361163d3ea3b3e94b096b9237294e2c6dd4b7bceaf3f8a07d"
      url "https://github.com/pb33f/printing-press/releases/download/v#{version}/printing-press_#{version}_linux_arm64.tar.gz"
    end
  end

  name "printing-press"
  desc "CLI for the pb33f Printing Press engine"
  homepage "https://github.com/pb33f/printing-press"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ppress"

  # No zap stanza required

end
