# This file was generated by GoReleaser. DO NOT EDIT.
cask "printing-press" do
  version "0.0.12"

  on_macos do
    on_intel do
      sha256 "c8e50988954a65d13d9957b0f3ca65439ff4e6bedd71d9b21a73693ea5d4f0e0"
      url "https://github.com/pb33f/printing-press/releases/download/v#{version}/printing-press_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d5af2eafa6fd182c5e5c5875c13d50067c1ab8c6464e535bdf21acfb397cba77"
      url "https://github.com/pb33f/printing-press/releases/download/v#{version}/printing-press_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3ab3b0de6713037bc4d9a2ff70333bf7e0b9d0d81ba136c41d37f7be00457225"
      url "https://github.com/pb33f/printing-press/releases/download/v#{version}/printing-press_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b1e61e3f57af281e2557ff4cd0eb23959c035821525f7a97a2e4f696e611b2cf"
      url "https://github.com/pb33f/printing-press/releases/download/v#{version}/printing-press_#{version}_linux_arm64.tar.gz"
    end
  end

  name "printing-press"
  desc "CLI for the pb33f Printing Press engine"
  homepage "https://github.com/pb33f/printing-press"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ppress"

  # No zap stanza required

end
