# This file was generated by GoReleaser. DO NOT EDIT.
cask "printing-press" do
  version "0.0.9"

  on_macos do
    on_intel do
      sha256 "c99e07b8b395910f4b600bc8f682757624315704c37c5c5b142385fcafaff370"
      url "https://github.com/pb33f/printing-press/releases/download/v#{version}/printing-press_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b1723dac4e94059bfbb6b320bc40e3d342c443ab012f98d9efc121f6c7f27620"
      url "https://github.com/pb33f/printing-press/releases/download/v#{version}/printing-press_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "63fa9834b239d09e403ec6e60d4236c97dcb5cd51f5a06011279f70756b5c0f4"
      url "https://github.com/pb33f/printing-press/releases/download/v#{version}/printing-press_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0445d51980dacadfbc8a337f294c78d44e9d0fd958088b413ac84b11073e1b50"
      url "https://github.com/pb33f/printing-press/releases/download/v#{version}/printing-press_#{version}_linux_arm64.tar.gz"
    end
  end

  name "printing-press"
  desc "CLI for the pb33f Printing Press engine"
  homepage "https://github.com/pb33f/printing-press"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pp"

  # No zap stanza required

end
