# This file was generated by GoReleaser. DO NOT EDIT.
cask "wiretap" do
  version "0.7.2"

  on_macos do
    on_intel do
      sha256 "f809c1e84d583b3d7a9204130a97af8ab07e2c0130435fd286f4b8905dad7666"
      url "https://github.com/pb33f/wiretap/releases/download/v#{version}/wiretap_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "63cf0ae40f8d8e5f46255b3e8dfe4a04f10dc0c3cb0153ef7939382c6757a9da"
      url "https://github.com/pb33f/wiretap/releases/download/v#{version}/wiretap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bf63ce09e8c8f1f7f85e0c22bf104fe8cd19f88b4e5cce4d99ebd003f544302f"
      url "https://github.com/pb33f/wiretap/releases/download/v#{version}/wiretap_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8875f48fe5109a7ec02728138007b43787cf6a8168ff33e9669253de869410e3"
      url "https://github.com/pb33f/wiretap/releases/download/v#{version}/wiretap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wiretap"
  desc "The worlds coolest OpenAPI compliance dev HTTP proxy"
  homepage "https://pb33f.io/wiretap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wiretap"

  # No zap stanza required

end
