# This file was generated by GoReleaser. DO NOT EDIT.
cask "wiretap" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "752585b12cc0ff480e117199dbeb1450aab3f5e36a0dd13103dbc807974d7ff5"
      url "https://github.com/pb33f/wiretap/releases/download/v#{version}/wiretap_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "095b5cd9a6a28427f63d08d03e18b8bb86001ed9b36984b9a661146822e19d4e"
      url "https://github.com/pb33f/wiretap/releases/download/v#{version}/wiretap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ab60c770067511ced625c77dadcbcb26b32f8a9bf06e7d68fe26dc30985fe8eb"
      url "https://github.com/pb33f/wiretap/releases/download/v#{version}/wiretap_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "38973ca9b807ae228659f5a1908b2a0b237ffd51bede7f584215d7057a359847"
      url "https://github.com/pb33f/wiretap/releases/download/v#{version}/wiretap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wiretap"
  desc "The worlds coolest OpenAPI compliance dev HTTP proxy"
  homepage "https://pb33f.io/wiretap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wiretap"

  # No zap stanza required

end
