# This file was generated by GoReleaser. DO NOT EDIT.
cask "wiretap" do
  version "0.5.8"

  on_macos do
    on_intel do
      url "https://github.com/pb33f/wiretap/releases/download/v#{version}/wiretap_#{version}_darwin_x86_64.tar.gz"
      sha256 "5d2b39c18327b8e0d2422b435a425838aa0a336ed2d685dfc812ba521c584c5d"
    end
    on_arm do
      url "https://github.com/pb33f/wiretap/releases/download/v#{version}/wiretap_#{version}_darwin_arm64.tar.gz"
      sha256 "9a0d76aa258a73e075840014f6a4d06de732d93e41ab52b86822d0cb4f445015"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pb33f/wiretap/releases/download/v#{version}/wiretap_#{version}_linux_x86_64.tar.gz"
      sha256 "a2f591472991c2df9e35162848aa921101baa5cf6592bd34ecdd88419291d0a6"
    end
    on_arm do
      url "https://github.com/pb33f/wiretap/releases/download/v#{version}/wiretap_#{version}_linux_arm64.tar.gz"
      sha256 "29337ce3d493265f7472dd581c40b89691bd6743fe131c5813d4ea31a1a9124c"
    end
  end

  name "wiretap"
  desc "The worlds coolest OpenAPI compliance dev HTTP proxy"
  homepage "https://pb33f.io/wiretap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wiretap"

  # No zap stanza required

end
